#!/usr/bin/env bash
# Script configures Nginx on a new ubuntu machine 
# Nginx should be listening on port 80
# Serves a page that would return 
# A Hello World string
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Starting nginx
sudo service nginx start
