#!/usr/bin/env bash
# Script configures a new ubuntu machine by installing
# Sets Nginx to listen on port 80
# finally serves a page that would 
# return a Hello World string

sudo apt-get  update -y
sudo apt-get install nginx -y

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Starting nginx
sudo service nginx start

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
