#!/usr/bin/env bash
#find out whats been keeping Nginx installation from listening on port 80
#Bash script finds fixes configres server to allow for
#Nginx to run and listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
